
make:
	webpack --mode development
dev:
	webpack-dev-server --port 8082 --hot --inline --open chrome
	
# push2prod:
# 	git push origin master
# 	git checkout  production
# 	git pull origin master
# 	git push origin production
# 	git checkout mastermake